CREATE DATABASE Restricciones
GO

USE Restricciones
GO

CREATE TABLE empleados
(
	ID INT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL, -- ESTA RESTRICCION NO PERMITE CAMPOS EN BLANCO
	EMAIL NVARCHAR(300) UNIQUE NOT NULL,
	EDAD INT CHECK (EDAD >= 18),
	FECHA_CUMPLEAÑOS DATE DEFAULT GETDATE()
)
GO

SELECT * FROM empleados

--- INSERTAR

INSERT INTO empleados (ID, NOMBRE, EMAIL, EDAD, FECHA_CUMPLEAÑOS)
VALUES
(715, 'ELIANA', 'eliana@gmail.com', 22)

-----------

CREATE TABLE ventas
(
	ID_VENTA INT IDENTITY(1,5) PRIMARY KEY,
	PRODUCTO NVARCHAR(400) DEFAULT 'NO REGISTRA',
	CANTIDAD FLOAT,
	ID_VENDEDOR INT,
	CONSTRAINT FK_ID_VENDEDOR_ID_EMPLEADOS FOREIGN KEY (ID_VENDEDOR)
	REFERENCES empleados(ID)
)

--- INSERTAR

INSERT INTO ventas (PRODUCTO, CANTIDAD, ID_VENDEDOR)
VALUES
('estribor', 8, 714)

SELECT * FROM ventas